

name: Pipeline
#Controls when the action will run
on:
  push:
    branches: [ main ]
    paths:
      - Chapter15/**
      - .github/workflows/pipeline.yaml
  workflow_dispatch:
# ENV to set reusable variables
env:
  ACRNAME: handsnakspipeline
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v4  

      - name: az CLI login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: ACR login
        run: az acr login -n $ACRNAME
        
      
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./Chapter15
          push: true
          tags: ${{ env.ACRNAME }}.azurecr.io/website/website:${{ github.run_number }}
